---
# Source: helmdemo/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: RELEASE-NAME-helmdemo
  labels:
    app: helmdemo
    chart: helmdemo-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmdemo
      release: RELEASE-NAME
  template:
    metadata:
      labels:
        app: helmdemo
        release: RELEASE-NAME
    spec:
      containers:
        - name: helmdemo
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
